In [5]:
import numpy as np

In [20]:
def find_cluster(representative,point):
    a=[np.linalg.norm((zj-point)) for zj in representative]
    j=a.index(min(a))
    return j

In [7]:
def find_representative(zj,cluster):
    a=[np.linalg.norm((zj-point)) for point in cluster]
    j=a.index(min(a))
    return cluster[j]

In [41]:
def k_means_single(X,Z,K,d):
    shape=(K,X.shape[0],X.shape[1])
    clusters=np.zeros(shape)
    print(clusters)
    for i in range(X.shape[0]):
        j=find_cluster(Z,X[i])
        print(X[i])
        clusters[j]=X[i]
        
        # print("cluster",clusters)
        Z[j]=find_representative(Z[j],clusters[j])
    # clusters,Z=np.array(clusters),np.array(Z)
    # print(">>>>>>>>>>>>>>>>>>>>>>>>>")
    # print("cluster",clusters)
    # # print(represntative.shape)
    return (clusters,Z)


In [42]:
X=np.array([[0,-6],[4,4],[0,0],[-5,2]])
K=2
Z=np.array([[-5,2],[0,-6]])
C=[]
while True:
    C,Z_updated=k_means_single(X,Z,K,2)
    if np.allclose(Z,Z_updated):
        break
    else:
        Z=Z_updated
        # print(Z,C)
for cluster in C:
    print("-------C-------")
    print(cluster)
for rep in Z:
    print("-----Z---------")
    print(rep)


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[ 0 -6]
[4 4]
[0 0]
[-5  2]
-------C-------
[[-5.  2.]
 [-5.  2.]
 [-5.  2.]
 [-5.  2.]]
-------C-------
[[ 0. -6.]
 [ 0. -6.]
 [ 0. -6.]
 [ 0. -6.]]
-----Z---------
[-5  2]
-----Z---------
[ 0 -6]


In [3]:
import numpy as np

def kmedoids(X, k,medoids):
  """Implements the K-medoids algorithm with the L1 norm.

  Args:
    X: A NumPy array of data points.
    k: The number of clusters.

  Returns:
    A tuple of two arrays:
      * The medoids.
      * The cluster assignments.
  """

  # Initialize the medoids
  medoids = X[np.random.choice(X.shape[0], size=k)]

  # Assign each data point to the nearest medoid
  cluster_assignments = np.argmin(np.linalg.norm(X[:, np.newaxis] - medoids, ord=1, axis=2), axis=1)

  while True:
    # Update the medoids
    new_medoids = []
    for i in range(k):
      cluster_i = X[cluster_assignments == i]
      new_medoid = np.median(cluster_i, axis=0)
      new_medoids.append(new_medoid)

    # Check for convergence
    if np.array_equal(medoids, new_medoids):
      break

    medoids = np.array(new_medoids)

  return medoids, cluster_assignments

In [4]:
X=np.array([[0,-6],[4,4],[0,0],[-5,2]])
K=2
Z=np.array([[-5,2],[0,-6]])
kmedoids(X,K,Z)

(array([[0., 0.],
        [4., 4.]]),
 array([0, 1, 0, 0]))