In [40]:
import torch

In [3]:
z=torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [4]:
z=torch.ones(5,3,dtype=torch.int16)
print(z)
print(z.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [5]:
a=torch.randn(2,2)
a

tensor([[-1.7954,  0.0740],
        [-1.7532,  0.6246]])

In [6]:
torch_tensor=torch.randn(3,3)
numpy_array=torch_tensor.numpy()
back_to_tensor=torch.from_numpy(numpy_array);
print(torch_tensor.type)
print(type( numpy_array))
print(back_to_tensor.type)

<built-in method type of Tensor object at 0x7f891c6dd4e0>
<class 'numpy.ndarray'>
<built-in method type of Tensor object at 0x7f891c6dfe70>


In [8]:
a=torch.randn(5,5)
b=torch.randn(5,5)
print(torch.matmul(a,b))

tensor([[-0.1391, -2.6807, -1.9350, -0.0152, -0.3484],
        [ 0.6577,  0.3639,  0.2972, -0.2796, -0.1291],
        [-1.3966, -0.6235,  0.1782,  0.3709,  0.3064],
        [ 0.7550,  0.5406,  1.0577, -0.6356,  1.1670],
        [-0.5536,  1.5947,  2.2881, -1.4525,  0.8056]])


In [15]:
a=torch.randn(5,5)
b=torch.randn(5,5)
print(a)
print(a[0,0])
print(a[0,0].item())
print(a[0,:]) #first row
print(a[:,1]) #second(0+1) column
print(a[0:3,1:3]) #combo (sub matrix from a)

tensor([[ 0.7301, -0.9104, -2.6658,  1.6842, -0.3405],
        [ 0.1372,  1.8791, -1.1791, -0.0139,  1.3080],
        [-0.5378, -1.4282,  1.0076,  1.1347, -1.5821],
        [-1.8361,  0.6192,  0.2163,  0.7942, -1.1972],
        [ 0.4986,  0.6443,  0.6936,  0.1490, -0.3498]])
tensor(0.7301)
0.7301007509231567
tensor([ 0.7301, -0.9104, -2.6658,  1.6842, -0.3405])
tensor([-0.9104,  1.8791, -1.4282,  0.6192,  0.6443])
tensor([[-0.9104, -2.6658],
        [ 1.8791, -1.1791],
        [-1.4282,  1.0076]])


In [16]:
#addition
print(a+b)

tensor([[ 0.3219, -1.1194, -1.3008,  1.6024, -0.3142],
        [ 1.0297,  3.3852, -1.0893, -0.4175,  0.5745],
        [-2.0883, -2.6152,  2.6032, -0.7417, -0.3527],
        [-0.5971,  0.0645,  1.3014,  1.0014, -1.7990],
        [-0.2787,  1.0220,  0.5162, -0.5536, -0.4871]])


In [17]:
#element wise multiplication
c=a*b
print(c)

tensor([[-0.2980,  0.1903, -3.6387, -0.1378, -0.0090],
        [ 0.1224,  2.8300, -0.1059,  0.0056, -0.9595],
        [ 0.8338,  1.6953,  1.6078, -2.1291, -1.9450],
        [-2.2748, -0.3435,  0.2347,  0.1645,  0.7204],
        [-0.3875,  0.2434, -0.1230, -0.1047,  0.0480]])


In [18]:
#vecort multiplication
print(a.matmul(b[:,0]))

tensor([ 5.3740,  2.4155,  0.0180,  2.8815, -0.2474])


In [19]:
a = torch.randn(5, 5)
print(a.size())

vec = a[:, 0]
print(vec.size())

torch.Size([5, 5])
torch.Size([5])


In [20]:
print(a.matmul(a))

tensor([[ -0.9977,  -2.3234,   0.8791,  -1.1811,   1.7791],
        [  4.0936,   0.6140,   6.2995,   3.9999,   3.3963],
        [-11.9253,  -2.8359,  10.0397,   2.4969,   6.0632],
        [-10.5668,  -4.8109,   5.1336,   0.2217,   3.3580],
        [ -3.4138,   2.1147,  -7.5642,  -5.4224,  -3.1687]])


In [24]:
vec_as_matrix=vec.view(5,1)
print(vec_as_matrix)

tensor([[-1.2361],
        [-1.1358],
        [ 1.9001],
        [ 0.2137],
        [ 2.9185]])


In [27]:

print(a)
# Add one to all elements
print(a.add_(1))
# Divide all elements by 2
print(a.div_(2))

# Set all elements to 0
print(a.zero_())

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [47]:
# Add a dummy dimension, e.g. (n, m) --> (n, m, 1)
a = torch.randn(10, 10)

# At the end
# print(a.unsqueeze(-1))
print(a.unsqueeze(-1).size())

# At the beginning
print(a.unsqueeze(0).size())

# In the middle
print(a.unsqueeze(1).size())

# What you give you can take away
print(a.unsqueeze(0).squeeze(0).size())

torch.Size([10, 10, 1])
torch.Size([1, 10, 10])
torch.Size([10, 1, 10])
torch.Size([10, 10])


In [48]:
# View things differently, i.e. flat
print(a.view(100, 1).size())

# Or not flat
print(a.view(50, 2).size())

# Copy data across a new dummy dimension!
a = torch.randn(2)
a = a.unsqueeze(-1)
print(a)
print(a.expand(2, 3))

torch.Size([100, 1])
torch.Size([50, 2])
tensor([[0.8433],
        [2.0102]])
tensor([[0.8433, 0.8433, 0.8433],
        [2.0102, 2.0102, 2.0102]])


In [49]:
# Check if you have it
do_i_have_cuda = torch.cuda.is_available()

if do_i_have_cuda:
    print('Using fancy GPUs')
    # One way
    a = a.cuda()
    a = a.cpu()

    # Another way
    device = torch.device('cuda')
    a = a.to(device)

    device = torch.device('cpu')
    a = a.to(device)
else:
    print('CPU it is!')

CPU it is!


In [52]:
# Batched matrix multiply
a = torch.randn(10, 5, 5)
b = torch.randn(10, 5, 5)

# The same as for i in 1 ... 10, c_i = a[i].mm(b[i])
c = a.bmm(b)
print(c.size())

torch.Size([10, 5, 5])


In [2]:
import sys

print("Python version:", sys.version)

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0]


In [4]:
# A tensor that will remember gradients
x = torch.randn(1, requires_grad=True)
print(x)

tensor([-0.6538], requires_grad=True)


In [5]:
print(x.grad)

None


In [6]:
y = x.exp()

In [7]:
y.backward() #To run the gradient computing magic, call '.backward()' on a variable.

In [8]:
print(x.grad, y)

tensor([0.5200]) tensor([0.5200], grad_fn=<ExpBackward>)


In [2]:
x=torch.empty(1)
print(x)
x=torch.empty(2,3)
print(x)

tensor([2.4754e-12])
tensor([[4.9066e-05, 4.5701e-41, 3.4856e+35],
        [3.0915e-41, 4.4842e-44, 0.0000e+00]])


In [5]:
print(x.size(1))
print(x.shape[1])

3
3


In [8]:
x=torch.tensor([1.1,2,3],requires_grad=True)
print(x)

tensor([1.1000, 2.0000, 3.0000], requires_grad=True)


In [11]:
x=torch.ones(2,2)
y=torch.ones(2,2)
z=x+y
print(z)

print(torch.add(x,y))
print(x.add(y))

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [29]:
x=torch.rand(4,4)
print(x.view(16))
print(x.view(1,16))
print(x.view(-1,8))

tensor([0.4450, 0.9876, 0.7287, 0.0646, 0.9852, 0.1018, 0.8159, 0.3569, 0.7966,
        0.1844, 0.2107, 0.1743, 0.8182, 0.1796, 0.4678, 0.5541])
tensor([[0.4450, 0.9876, 0.7287, 0.0646, 0.9852, 0.1018, 0.8159, 0.3569, 0.7966,
         0.1844, 0.2107, 0.1743, 0.8182, 0.1796, 0.4678, 0.5541]])
tensor([[0.4450, 0.9876, 0.7287, 0.0646, 0.9852, 0.1018, 0.8159, 0.3569],
        [0.7966, 0.1844, 0.2107, 0.1743, 0.8182, 0.1796, 0.4678, 0.5541]])


In [50]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.1851, -0.7371, -0.5376], requires_grad=True)


In [51]:
y=2+x

In [66]:
print(y)
z=y**2
print(z)

tensor(1.6368, grad_fn=<MeanBackward0>)
tensor(2.6791, grad_fn=<PowBackward0>)


In [67]:
z.backward()
print(x.grad)

tensor([4.2736, 4.2736, 4.2736])
