In [3]:
import numpy as np

In [4]:
x=np.array([1,2,3])
x.shape

(3,)

In [5]:
y=np.array([[1,2,3],[4,5,6]])

In [6]:
y.shape

(2, 3)

In [7]:
z=np.array([[1,2],[3,4],[6,7]])

In [8]:
z.shape

(3, 2)

In [9]:
print(y)
np.transpose(y)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
A=np.array([[1,2,3],[4,6,9],[6,7,8]])
B=np.array([[4,6,1],[9,7,8],[1,2,3]])
print(A*B) # ELEMENT X ELEMENT 
print("----------------------------")
print(np.matmul(A,B)) # MATRIX MULTIPLICATION 

[[ 4 12  3]
 [36 42 72]
 [ 6 14 24]]
----------------------------
[[ 25  26  26]
 [ 79  84  79]
 [ 95 101  86]]


In [11]:
np.exp(x) #exponential graph mapped with the passed areay

array([ 2.71828183,  7.3890561 , 20.08553692])

In [12]:
a=np.array([0,0.5,1,1.5,2,2.5,2])

In [13]:
result=np.exp(a);

In [14]:
print(result)

[ 1.          1.64872127  2.71828183  4.48168907  7.3890561  12.18249396
  7.3890561 ]


In [15]:
np.sin(a)

array([0.        , 0.47942554, 0.84147098, 0.99749499, 0.90929743,
       0.59847214, 0.90929743])

In [16]:
np.tanh(a) #hyperbolic func

array([0.        , 0.46211716, 0.76159416, 0.90514825, 0.96402758,
       0.9866143 , 0.96402758])

In [17]:
def operation(h,w):
    A=np.random.random([h,w])
    B=np.random.random([h,w])
    s=A+B

    return (A,B,s)
operation(3,3)

(array([[0.29863255, 0.21673196, 0.2116808 ],
        [0.36892363, 0.61051257, 0.92860758],
        [0.7945133 , 0.25476441, 0.81167313]]),
 array([[0.07435715, 0.39098029, 0.46057012],
        [0.00779363, 0.424755  , 0.88228761],
        [0.28781722, 0.40353257, 0.95495798]]),
 array([[0.3729897 , 0.60771225, 0.67225092],
        [0.37671725, 1.03526756, 1.81089519],
        [1.08233052, 0.65829697, 1.76663111]]))

In [18]:
np.random.random([3,3])

array([[0.66868523, 0.39762961, 0.68006919],
       [0.56366545, 0.04480035, 0.99112791],
       [0.10905499, 0.22613301, 0.67938174]])

In [19]:
print(a) #max and min
print(np.max(a))
a.max()

[0.  0.5 1.  1.5 2.  2.5 2. ]
2.5


2.5

In [20]:
np.random.random() #random between 0 to 1

0.8064346944664477

In [21]:
np.random.random([2,10]) #random array

array([[0.89788683, 0.94459567, 0.63146999, 0.05218254, 0.10484129,
        0.58587257, 0.3027385 , 0.1026873 , 0.49744011, 0.90077926],
       [0.90310191, 0.53604188, 0.35803015, 0.61459264, 0.19338225,
        0.46400545, 0.43815391, 0.54049452, 0.90086169, 0.64981215]])

In [22]:
np.linalg.norm(a) #normal of matrix

4.2130748865881795

In [23]:
A=np.array([1,2,3,4,5])
B=np.array([7,8,9,0,6])
def func(A,B):
    sum=A+B
    return np.linalg.norm(sum)

func(A,B)

21.095023109728988

In [24]:
def neural_network(inputs, weights):
    wt = np.transpose(weights)
    res = np.matmul(wt, inputs)

    res = np.tanh(res)
    return res


neural_network(np.array([[1], [3]]), np.array([[3], [5]]))

# 1 , 3
# 3 , 5


array([[1.]])

In [25]:
def func(x,y):
    if x<=y:
        return x*y
    else:
        return x/y
func(1,2)

2

In [60]:
# vectorizing a scalar function
def v_fn(x,y):
    def fn(x, y):
        if x <= y:
            fx = x*y
        else:
            fx = x/y
        return fx
    res=np.vectorize(fn)(x,y)
    return res

v_fn(np.array([1,2]),np.array([1,3]))

# v_fn(np.array([1,2]),np.array([1,3]))

array([1, 6])