In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
x.shape

(3,)

In [3]:
y=np.array([[1,2,3],[4,5,6]])

In [4]:
y.shape

(2, 3)

In [5]:
z=np.array([[1,2],[3,4],[6,7]])

In [6]:
z.shape

(3, 2)

In [11]:
print(y)
np.transpose(y)

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
A=np.array([[1,2,3],[4,6,9],[6,7,8]])
B=np.array([[4,6,1],[9,7,8],[1,2,3]])
print(A*B) # ELEMENT X ELEMENT 
print("----------------------------")
print(np.matmul(A,B)) # MATRIX MULTIPLICATION 

[[ 4 12  3]
 [36 42 72]
 [ 6 14 24]]
----------------------------
[[ 25  26  26]
 [ 79  84  79]
 [ 95 101  86]]


In [12]:
np.exp(x) #exponential graph mapped with the passed areay

array([ 2.71828183,  7.3890561 , 20.08553692])

In [18]:
a=np.array([0,0.5,1,1.5,2,2.5,2])

In [20]:
result=np.exp(a);

In [21]:
print(result)

[ 1.          1.64872127  2.71828183  4.48168907  7.3890561  12.18249396
  7.3890561 ]


In [22]:
np.sin(a)

array([0.        , 0.47942554, 0.84147098, 0.99749499, 0.90929743,
       0.59847214, 0.90929743])

In [23]:
np.tanh(a) #hyperbolic func

array([0.        , 0.46211716, 0.76159416, 0.90514825, 0.96402758,
       0.9866143 , 0.96402758])

In [31]:
def operation(h,w):
    A=np.random.random([h,w])
    B=np.random.random([h,w])
    s=A+B

    return (A,B,s)
operation(3,3)

(array([[0.54596232, 0.17559118, 0.25562211],
        [0.500309  , 0.32723951, 0.43888255],
        [0.69533427, 0.04872241, 0.74204651]]),
 array([[0.11389717, 0.33303869, 0.59038835],
        [0.36890604, 0.53359853, 0.81579476],
        [0.77384828, 0.57234042, 0.11388965]]),
 array([[0.65985949, 0.50862987, 0.84601046],
        [0.86921504, 0.86083804, 1.25467731],
        [1.46918255, 0.62106283, 0.85593616]]))

In [30]:
np.random.random([3,3])

array([[0.65487241, 0.29032292, 0.59414975],
       [0.79626263, 0.5999804 , 0.58205879],
       [0.18456719, 0.6761018 , 0.8181503 ]])