In [1]:
import numpy as np

In [2]:
np.array([1,2])

array([1, 2])

In [3]:
a=np.array([1,2])

In [4]:
a+1

array([2, 3])

In [5]:
a*2

array([2, 4])

In [6]:
random=np.random.random([2,3])
print(random)

[[0.61289905 0.6386084  0.20523222]
 [0.09698906 0.81239596 0.32948997]]


In [7]:
def func(n):
    return np.random.random([n,1])
func(3)

array([[0.51543042],
       [0.36831243],
       [0.59690222]])

In [8]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.

