In [1]:
print("Hi")

Hi


In [4]:
import numpy as np;

In [5]:
a=np.array([1,2])

In [7]:
a+1

array([2, 3])

In [13]:
type (tu)

str

In [7]:
a+2

array([3, 4])

In [9]:
a*5

array([ 5, 10])

In [11]:
a/2

array([0.5, 1. ])

In [12]:
a//2

array([0, 1])

In [13]:
a

array([1, 2])

In [14]:
a=np.zeros([2,3])

In [16]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones([6,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.identity([3,3])

TypeError: 'list' object cannot be interpreted as an integer

In [20]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.identity(2,int)

array([[1, 0],
       [0, 1]])