In [3]:
import numpy as np

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
type(np.array([1,2]))

numpy.ndarray

In [12]:
zeros_array=np.zeros((9,9))
print(zeros_array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [18]:
np.arange(10,50,5) #from,to,step

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.random.randint(1,100,5)#any 5 random number between 1 to 100

array([28, 29, 76, 89,  1])

In [29]:
a=np.full((3,3),9)
a.shape

(3, 3)

In [36]:
a=np.random.random((3,5))
a

array([[0.23667105, 0.69199788, 0.96739273, 0.31068748, 0.87884038],
       [0.75102135, 0.49278696, 0.59227494, 0.35778351, 0.47655922],
       [0.26252959, 0.91467125, 0.6303779 , 0.88479379, 0.42568173]])

In [38]:
a.shape=(5,3)
a

array([[0.23667105, 0.69199788, 0.96739273],
       [0.31068748, 0.87884038, 0.75102135],
       [0.49278696, 0.59227494, 0.35778351],
       [0.47655922, 0.26252959, 0.91467125],
       [0.6303779 , 0.88479379, 0.42568173]])

In [65]:
# stacking
a=np.random.randint(10,100,(2,3))
b=np.random.randint(10,100,(2,3))





In [66]:
np.hstack((b,a))#horizontal stack

array([[32, 66, 98, 89, 51, 35],
       [19, 86, 38, 43, 76, 66]])

In [67]:
np.vstack((a,b))#verticle stack

array([[89, 51, 35],
       [43, 76, 66],
       [32, 66, 98],
       [19, 86, 38]])

In [68]:
np.column_stack((b,a))

array([[32, 66, 98, 89, 51, 35],
       [19, 86, 38, 43, 76, 66]])