# Estimate or Predictor or Models

### In predictors we have FIT and TRANSFORM
`<predictor>.fit` and `<predictor>.predict`

In [9]:
import sklearn
print(sklearn.__version__)

1.3.0


In [10]:
from sklearn.linear_model import Perceptron

In [11]:
#train
model=Perceptron(random_state=42)
x=[
    [1,2,4],
    [11,12,13]
   ]
y=[1,-1]
model.fit(x,y)



Perceptron(random_state=42)

In [12]:
#predict train set
model.predict(x) #train data

array([ 1, -1])

In [14]:
#predict test set
model.predict([[3,4,5]]) #test data

array([-1])

In [16]:
#probality
# model.predict_proba([[15,6,7]]) # applicable for some selected model

In [19]:
#accuracy of model on train data
model.score(x,y)

1.0

In [20]:
#accuracy of model on test data
model.score([[3,4,5]],[-1])

1.0

# Transformer or Pre-processors

### In transformers we have FIT and TRANSFORM
`<transformer>.fit` and `<transformer>.transform`

In [29]:
#standard Normal distribution
from sklearn.preprocessing import StandardScaler
import numpy as np

x=np.array([1,2,3,4,6,7]).reshape(-1,1)

#scale data according to computed scalar values
Fx=StandardScaler().fit(x)

Fx.transform(x)

array([[-1.33978769],
       [-0.86692145],
       [-0.3940552 ],
       [ 0.07881104],
       [ 1.02454353],
       [ 1.49740977]])

In [31]:
#StandardScaler().fit_transform(x) #similar to above

In [32]:
#transform without fit (for test set) dpend on the params of train set
test_set=np.array([1.1,2.1,3.1,4.1,6.1,7.1]).reshape(-1,1)

Fx.transform(test_set)


array([[-1.29250107],
       [-0.81963482],
       [-0.34676858],
       [ 0.12609766],
       [ 1.07183015],
       [ 1.5446964 ]])

# Pipelining
### to execute some task in some specific order

In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron,LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

pipe_ex=make_pipeline(
    StandardScaler(), #transofrm
    Perceptron(),
    Perceptron(),
    LogisticRegression(),
    StandardScaler(),
)
pipe=make_pipeline(
    StandardScaler(), #transofrm
    Perceptron(),
)

In [3]:
x,y=load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=0)
pipe.fit(X_train,y_train)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('perceptron', Perceptron())])

In [5]:
accuracy_score(pipe.predict(X_test),y_test)

0.8421052631578947

# Model Evaluation
### like cross validation

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.datasets import load_iris

x,y=load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=0)


perceptron=Perceptron()

result=cross_validate(perceptron,x,y,cv=3)

result['test_score'] #number of partition


array([0.74, 0.76, 0.66])

# Parameter Tunning


In [13]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_iris

x,y=load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=0)

model = SGDClassifier(loss='hinge')

param_grid = {
    'alpha': [0.0001, 0.001, 0.01],
    'l1_ratio': [0.1, 0.3, 0.5],
    'max_iter': [100, 200, 500]
}
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(x, y)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_




In [14]:
best_model

SGDClassifier(alpha=0.001, l1_ratio=0.3, max_iter=200)

In [16]:
best_params

{'alpha': 0.001, 'l1_ratio': 0.3, 'max_iter': 200}